version: "3.1"

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/
    links:
      - db

  db:
    image: mysql
    container_name: classicmodels
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_ROOT_DATABASE=classicmodels
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
